package bi.uburaro.core.types;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;

@Data
@NoArgsConstructor
public class ItemType {
    public static final String ITEM_TYPE = "item";
    public static final String ITEM_NUMBER = "itemNumber";
    public static final String ID = "id";
    public static final String PK = "pk";
    public static final String DATE_CREATED = "dateCreated";
    public static final String DATE_MODIFIED= "dateModified";
    public static final String MODIFICATION_LOGS= "modificationLogs";

    private String id;
    /**
     * the primary key, will be generated by the concatenating ItemNumber and the timestamp of the object
     */
    private String pk;
    private String itemType;
    private Date dateCreated;
    private Date dateModified;
    private List<ModificationLogType> modificationLogs;

    public ItemType(String id) {
        this.id = id;
    }
}
