version: '3.8'

services:
  mysql:
    image: mysql:9.0.1
    container_name: uburaro_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: uburaro
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./uburaro.sql:/docker-entrypoint-initdb.d/dump.sql

    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
